// Code generated by go generate; DO NOT EDIT.
// This file was generated by main
package main

func (rs *ResetableStruct) Reset() {
	rs.i = 0
	rs.str = ""
	if rs.strP != nil {
		*rs.strP = ""
	}

	rs.s = rs.s[:0]
	clear(rs.m)
}
