package main

const genFileName = "reset.gen.go"

const tmpResetMethod = `// Code generated by go generate; DO NOT EDIT.
// This file was generated by {{.PackageName}}
package {{.PackageName}}

{{- range .Structs}}

func (rs *{{.Name}}) Reset() {
	{{- range .Fields}}
	{{- if .IsBasic}}
	// Поле {{.Name}} - базовый тип ({{.TypeString}})
	rs.{{.Name}} = {{.ZeroValue}}
	{{- else if .IsPointerBasic}}
	// Поле {{.Name}} - указатель на базовый тип ({{.TypeString}})
	if rs.{{.Name}} != nil {
		*rs.{{.Name}} = {{.ZeroValue}}
	}
	{{- else if .IsSlice}}
	// Поле {{.Name}} - слайс ({{.TypeString}})
	rs.{{.Name}} = rs.{{.Name}}[:0]
	{{- else if .IsMap}}
	// Поле {{.Name}} - мапа ({{.TypeString}})
	clear(rs.{{.Name}})
	{{- else if .HasResetMethod}}
	// Поле {{.Name}} - структура ({{.TypeString}})
	if resetter, ok := rs.{{.Name}}.(interface{ Reset() }); ok && rs.{{.Name}} != nil {
        resetter.Reset()
    }
	{{- end}}
	{{- end}}
}
{{- end}}
`
